### ISSUE TITLE
[Question] How to do a unit test for publish endpoints?

### ISSUE THREAD

**Issue by diavrank** [peerlibrary/meteor-middleware#4]
Hello, I'm stating to unit tests (using `meteortesting:mocha`) for my endpoints. I use **validated method** package for my meteor methods and there is a simple way to do unit tests for those methods. On the other hand, I use this meteor package to make my publications and I wonder if there is a way to do unit tests for publish endpoints?

Can I use a method (like `_execute` in validated method) from **publishEndpoint constant** to execute the function of my publication?

**Comment by mitar** [comment]
I use [classy-test](https://github.com/peerlibrary/meteor-classy-test) for unit testing Meteor. So you setup publish endpoint on the server and then you subscribe from the client, testing the results. It allows interleaving client and server blocks so you can write a test this way.
